name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      env:
        CPANEL_USER: ${{ secrets.CPANEL_USER }} # Usuário do cPanel
        CPANEL_TOKEN: ${{ secrets.CPANEL_TOKEN }} # Token do cPanel
        WEBSOCKET_TOKEN: ${{ secrets.WEBSOCKET_TOKEN }} # Token do script PHP
        CPANEL_HOST: "vmi1477516.contaboserver.net"
        CPANEL_PORT: "2083"
        REPOSITORY_ROOT: "/home/megalochat/public_html/restart/"
        KILL_PROCESS_URL: "http://seu-servidor.com/kill_process.php" # Substitua pelo URL real
      run: |
        curl -X POST \
          -H "Authorization: cpanel ${CPANEL_USER}:${CPANEL_TOKEN}" \
          -H "Content-Type: multipart/form-data" \
          -F "repository_root=${REPOSITORY_ROOT}" \
          -F "branch=main" \
          https://${CPANEL_HOST}:${CPANEL_PORT}/execute/VersionControl/update

        curl -X POST ${KILL_PROCESS_URL} \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${WEBSOCKET_TOKEN}"