name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      env:
        CPANEL_USER: ${{ secrets.CPANEL_USER }} # Usuário do cPanel
        CPANEL_TOKEN: ${{ secrets.CPANEL_TOKEN }} # Token do cPanel
        WEBSOCKET_TOKEN: ${{ secrets.WEBSOCKET_TOKEN }} # Token do script PHP
        CPANEL_HOST: "vmi1477516.contaboserver.net"
        CPANEL_PORT: "2083"
        REPOSITORY_ROOT: "/home/megalochat/public_html/websocket"
        KILL_PROCESS_URL: "http://megalochat.com/restart/" # Substitua pelo URL real
      run: |
        curl -X POST \
          -H "Authorization: cpanel megalochat:NJ6Y92K4YE519BV296T16QGHXCIJMGY1" \
          -H "Content-Type: multipart/form-data" \
          -F "repository_root=/home/megalochat/public_html/restart/" \
          -F "branch=main" \
          https://vmi1477516.contaboserver.net:2083/execute/VersionControl/update

        curl -X POST ${KILL_PROCESS_URL} \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${WEBSOCKET_TOKEN}"