name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      run: |
        curl -X POST \
          -H "Authorization: cpanel megalochat:NJ6Y92K4YE519BV296T16QGHXCIJMGY1" \
          -H "Content-Type: multipart/form-data" \
          -F "repository_root=/home/megalochat/public_html/restart" \
          -F "branch=main" \
          https://vmi1477516.contaboserver.net:2083/execute/VersionControl/update

        curl -X POST http://seu-servidor.com/kill_process.php \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer 7fH2xd9QEBo1pzNVRaK8yJXwuMZqTGfiYr5nO6LSbcCmWgDtxvUPeMKAjRh3vFZlNTX0YiGsHd"
